package com.demo.models;
// Generated Dec 29, 2021, 9:30:54 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountPackId generated by hbm2java
 */
@Embeddable
public class AccountPackId implements java.io.Serializable {

	private int accountId;
	private int packId;

	public AccountPackId() {
	}

	public AccountPackId(int accountId, int packId) {
		this.accountId = accountId;
		this.packId = packId;
	}

	@Column(name = "account_id", nullable = false)
	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	@Column(name = "pack_id", nullable = false)
	public int getPackId() {
		return this.packId;
	}

	public void setPackId(int packId) {
		this.packId = packId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountPackId))
			return false;
		AccountPackId castOther = (AccountPackId) other;

		return (this.getAccountId() == castOther.getAccountId()) && (this.getPackId() == castOther.getPackId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccountId();
		result = 37 * result + this.getPackId();
		return result;
	}

}
