package com.demo.models;
// Generated Jan 18, 2022, 12:54:17 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountPack generated by hbm2java
 */
@Entity
@Table(name = "account_pack", catalog = "dbproject4")
public class AccountPack implements java.io.Serializable {

	private Integer accountPackId;
	private Account account;
	private Pack pack;
	private Date startDate;
	private boolean status;

	//ntohing
	public AccountPack() {
	}

	public AccountPack(Account account, Pack pack, Date startDate, boolean status) {
		this.account = account;
		this.pack = pack;
		this.startDate = startDate;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "account_pack_id", unique = true, nullable = false)
	public Integer getAccountPackId() {
		return this.accountPackId;
	}

	public void setAccountPackId(Integer accountPackId) {
		this.accountPackId = accountPackId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pack_id", nullable = false)
	public Pack getPack() {
		return this.pack;
	}

	public void setPack(Pack pack) {
		this.pack = pack;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
