package com.demo.models;
// Generated Dec 29, 2021, 9:30:54 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * History generated by hbm2java
 */
@Entity
@Table(name = "history", catalog = "dbproject4")
public class History implements java.io.Serializable {

	private HistoryId id;
	private Account account;
	private Quiz quiz;

	public History() {
	}

	public History(HistoryId id, Account account, Quiz quiz) {
		this.id = id;
		this.account = account;
		this.quiz = quiz;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "historyId", column = @Column(name = "history_id", nullable = false)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false, length = 10)),
			@AttributeOverride(name = "quizId", column = @Column(name = "quiz_id", nullable = false)),
			@AttributeOverride(name = "accountId", column = @Column(name = "account_id", nullable = false)),
			@AttributeOverride(name = "status", column = @Column(name = "status", nullable = false)) })
	public HistoryId getId() {
		return this.id;
	}

	public void setId(HistoryId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false, insertable = false, updatable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "quiz_id", nullable = false, insertable = false, updatable = false)
	public Quiz getQuiz() {
		return this.quiz;
	}

	public void setQuiz(Quiz quiz) {
		this.quiz = quiz;
	}

}
