package com.demo.models;
// Generated Dec 29, 2021, 9:30:54 PM by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pack generated by hbm2java
 */
@Entity
@Table(name = "pack", catalog = "dbproject4")
public class Pack implements java.io.Serializable {

	private Integer packId;
	private String title;
	private int expiry;
	private BigDecimal fee;
	private String description;
	private boolean status;
	private Set<AccountPack> accountPacks = new HashSet<AccountPack>(0);

	public Pack() {
	}

	public Pack(String title, int expiry, BigDecimal fee, String description, boolean status) {
		this.title = title;
		this.expiry = expiry;
		this.fee = fee;
		this.description = description;
		this.status = status;
	}

	public Pack(String title, int expiry, BigDecimal fee, String description, boolean status,
			Set<AccountPack> accountPacks) {
		this.title = title;
		this.expiry = expiry;
		this.fee = fee;
		this.description = description;
		this.status = status;
		this.accountPacks = accountPacks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pack_id", unique = true, nullable = false)
	public Integer getPackId() {
		return this.packId;
	}

	public void setPackId(Integer packId) {
		this.packId = packId;
	}

	@Column(name = "title", nullable = false, length = 300)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "expiry", nullable = false)
	public int getExpiry() {
		return this.expiry;
	}

	public void setExpiry(int expiry) {
		this.expiry = expiry;
	}

	@Column(name = "fee", nullable = false, precision = 10)
	public BigDecimal getFee() {
		return this.fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pack")
	public Set<AccountPack> getAccountPacks() {
		return this.accountPacks;
	}

	public void setAccountPacks(Set<AccountPack> accountPacks) {
		this.accountPacks = accountPacks;
	}

}
