package com.demo.models;
// Generated Jan 18, 2022, 12:54:17 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "dbproject4")
public class Question implements java.io.Serializable {

	private Integer questionId;
	private Quiz quiz;
	private String title;
	private String explainDetail;
	private boolean status;
	private String typeAnswerChoice;
	private Set<Answer> answers = new HashSet<Answer>(0);

	public Question() {
	}

	public Question(Quiz quiz, String title, String explainDetail, boolean status, String typeAnswerChoice) {
		this.quiz = quiz;
		this.title = title;
		this.explainDetail = explainDetail;
		this.status = status;
		this.typeAnswerChoice = typeAnswerChoice;
	}

	public Question(Quiz quiz, String title, String explainDetail, boolean status, String typeAnswerChoice,
			Set<Answer> answers) {
		this.quiz = quiz;
		this.title = title;
		this.explainDetail = explainDetail;
		this.status = status;
		this.typeAnswerChoice = typeAnswerChoice;
		this.answers = answers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "question_id", unique = true, nullable = false)
	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "quiz_id", nullable = false)
	public Quiz getQuiz() {
		return this.quiz;
	}

	public void setQuiz(Quiz quiz) {
		this.quiz = quiz;
	}

	@Column(name = "title", nullable = false, length = 250)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "explain_detail", nullable = false, length = 65535)
	public String getExplainDetail() {
		return this.explainDetail;
	}

	public void setExplainDetail(String explainDetail) {
		this.explainDetail = explainDetail;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "type_answer_choice", nullable = false, length = 20)
	public String getTypeAnswerChoice() {
		return this.typeAnswerChoice;
	}

	public void setTypeAnswerChoice(String typeAnswerChoice) {
		this.typeAnswerChoice = typeAnswerChoice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set<Answer> getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set<Answer> answers) {
		this.answers = answers;
	}

}
