package com.demo.models;
// Generated Jan 15, 2022, 8:47:44 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Quiz generated by hbm2java
 */
@Entity
@Table(name = "quiz", catalog = "dbproject4")
public class Quiz implements java.io.Serializable {

	private Integer quizId;
	private Account account;
	private Category category;
	private String title;
	private String description;
	private int times;
	private byte timer;
	private boolean fee;
	private String image;
	private boolean status;	
	private Date dateCreated;
	private Set<RatingComment> ratingComments = new HashSet<RatingComment>(0);
	private Set<History> histories = new HashSet<History>(0);
	private Set<Question> questions = new HashSet<Question>(0);

	public Quiz() {
	}

	public Quiz(Account account, Category category, String title, String description, int times, byte timer,
			boolean fee, String image, boolean status, Date dateCreated) {
		this.account = account;
		this.category = category;
		this.title = title;
		this.description = description;
		this.times = times;
		this.timer = timer;
		this.fee = fee;
		this.image = image;
		this.status = status;
		this.dateCreated = dateCreated;
	}

	public Quiz(Account account, Category category, String title, String description, int times, byte timer,
			boolean fee, String image, boolean status, Date dateCreated, Set<RatingComment> ratingComments,
			Set<History> histories, Set<Question> questions) {
		this.account = account;
		this.category = category;
		this.title = title;
		this.description = description;
		this.times = times;
		this.timer = timer;
		this.fee = fee;
		this.image = image;
		this.status = status;
		this.dateCreated = dateCreated;
		this.ratingComments = ratingComments;
		this.histories = histories;
		this.questions = questions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "quiz_id", unique = true, nullable = false)
	public Integer getQuizId() {
		return this.quizId;
	}

	public void setQuizId(Integer quizId) {
		this.quizId = quizId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "title", nullable = false, length = 250)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "times", nullable = false)
	public int getTimes() {
		return this.times;
	}

	public void setTimes(int times) {
		this.times = times;
	}

	@Column(name = "timer", nullable = false)
	public byte getTimer() {
		return this.timer;
	}

	public void setTimer(byte timer) {
		this.timer = timer;
	}

	@Column(name = "fee", nullable = false)
	public boolean isFee() {
		return this.fee;
	}

	public void setFee(boolean fee) {
		this.fee = fee;
	}

	@Column(name = "image", nullable = false, length = 65535)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 26)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quiz")
	public Set<RatingComment> getRatingComments() {
		return this.ratingComments;
	}

	public void setRatingComments(Set<RatingComment> ratingComments) {
		this.ratingComments = ratingComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quiz")
	public Set<History> getHistories() {
		return this.histories;
	}

	public void setHistories(Set<History> histories) {
		this.histories = histories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quiz")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
