package com.demo.models;
// Generated Jan 17, 2022, 9:56:49 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * RatingComment generated by hbm2java
 */
@Entity
@Table(name = "rating_comment", catalog = "dbproject4")
public class RatingComment implements java.io.Serializable {

	private Integer ratingCommentId;
	private Account account;
	private Quiz quiz;
	private byte star;
	private String comment;
	private boolean status;
	private Date createDate;
	
	public RatingComment() {
	}

	public RatingComment(Account account, Quiz quiz, byte star, String comment, boolean status, Date createDate) {
		this.account = account;
		this.quiz = quiz;
		this.star = star;
		this.comment = comment;
		this.status = status;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rating_comment_id", unique = true, nullable = false)
	public Integer getRatingCommentId() {
		return this.ratingCommentId;
	}

	public void setRatingCommentId(Integer ratingCommentId) {
		this.ratingCommentId = ratingCommentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "quiz_id", nullable = false)
	public Quiz getQuiz() {
		return this.quiz;
	}

	public void setQuiz(Quiz quiz) {
		this.quiz = quiz;
	}

	@Column(name = "star")
	public byte getStar() {
		return this.star;
	}

	public void setStar(byte star) {
		this.star = star;
	}

	@Column(name = "comment", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
