package com.demo.models;
// Generated Jan 25, 2022, 3:09:40 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Salary generated by hbm2java
 */
@Entity
@Table(name = "salary", catalog = "dbproject4")
public class Salary implements java.io.Serializable {

	private Integer salaryId;
	private Account account;
	private float salary;
	private Date createDate;
	private boolean status;
	private int totalClickQuiz;
	private boolean acceptPayment;

	public Salary() {
	}

	public Salary(Account account, float salary, Date createDate, boolean status, int totalClickQuiz,
			boolean acceptPayment) {
		this.account = account;
		this.salary = salary;
		this.createDate = createDate;
		this.status = status;
		this.totalClickQuiz = totalClickQuiz;
		this.acceptPayment = acceptPayment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "salary_id", unique = true, nullable = false)
	public Integer getSalaryId() {
		return this.salaryId;
	}

	public void setSalaryId(Integer salaryId) {
		this.salaryId = salaryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "salary", nullable = false, precision = 10, scale = 2)
	public float getSalary() {
		return this.salary;
	}

	public void setSalary(float salary) {
		this.salary = salary;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "total_click_quiz", nullable = false)
	public int getTotalClickQuiz() {
		return this.totalClickQuiz;
	}

	public void setTotalClickQuiz(int totalClickQuiz) {
		this.totalClickQuiz = totalClickQuiz;
	}

	@Column(name = "accept_payment", nullable = false)
	public boolean isAcceptPayment() {
		return this.acceptPayment;
	}

	public void setAcceptPayment(boolean acceptPayment) {
		this.acceptPayment = acceptPayment;
	}

}
