package com.demo.models;
// Generated Dec 3, 2021, 10:25:53 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mail generated by hbm2java
 */
@Entity
@Table(name = "mail", catalog = "dbproject4")
public class Mail implements java.io.Serializable {

	private Integer mailId;
	private String title;
	private String emailUser;
	private String fullname;
	private String phoneNumber;
	private String content;
	private String replyContent;
	private Date sendDate;
	private Date replyDate;
	private boolean checked;
	private boolean status;

	public Mail() {
	}

	public Mail(String title, String emailUser, String fullname, String phoneNumber, String content,
			String replyContent, Date sendDate, Date replyDate, boolean checked, boolean status) {
		this.title = title;
		this.emailUser = emailUser;
		this.fullname = fullname;
		this.phoneNumber = phoneNumber;
		this.content = content;
		this.replyContent = replyContent;
		this.sendDate = sendDate;
		this.replyDate = replyDate;
		this.checked = checked;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mail_id", unique = true, nullable = false)
	public Integer getMailId() {
		return this.mailId;
	}

	public void setMailId(Integer mailId) {
		this.mailId = mailId;
	}

	@Column(name = "title", nullable = false, length = 250)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "email_user", nullable = false, length = 100)
	public String getEmailUser() {
		return this.emailUser;
	}

	public void setEmailUser(String emailUser) {
		this.emailUser = emailUser;
	}

	@Column(name = "fullname", nullable = false, length = 100)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "phone_number", nullable = false, length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "reply_content", nullable = false, length = 65535)
	public String getReplyContent() {
		return this.replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "send_date", nullable = false, length = 26)
	public Date getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reply_date", nullable = false, length = 26)
	public Date getReplyDate() {
		return this.replyDate;
	}

	public void setReplyDate(Date replyDate) {
		this.replyDate = replyDate;
	}

	@Column(name = "checked", nullable = false)
	public boolean isChecked() {
		return this.checked;
	}

	public void setChecked(boolean checked) {
		this.checked = checked;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
